import Head from "next/head";

import Link from "next/link";
import { TextField } from "@mui/material";

export default function Home() {
  return (
    <div class="boxed">
      <Head>
        <title>Pandit Plastic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center">
        <div></div>
        <form className="flex flex-col">
          <TextField label="Name" variant="outlined" />
          <TextField label="Description" variant="outlined" />
          <TextField label="MRP" variant="outlined" />
          <TextField label="Discount" variant="outlined" />
          <TextField label="Price" variant="outlined" />
          <TextField label="Weight" variant="outlined" />
        </form>
      </div>
    </div>
  );
}
